### PR TITLE
Dark mode

### PR DESCRIPTION
**Pull request by DenizCankurtaran**
Dark mode is working, but there are two small issues.

First a design choice.
Currently the button, to switch between modes, is in the Welcome.vue, but that means there is no way to switch modes in any other page.
I could add it to the navigation bar or leave it in the Welcome.vue.

Second problem.
Vue uses the light theme as standard, so if you chose dark mode and reload the page, light mode would be displayed.
I solved the problem by adding a attribute in the user store.
Once you reload, a created() method in Kubeportal.vue will check the current theme.

That works for all .vues that are part of Kubeportal.vue, which are all except one, the Login.vue.
I could solve it 'ugly', by also asking what the current theme is in Login.vue, but I wondered if you could think of a better solution.

### CODE REVIEW

**Comment by kat-hi** [comment]
@troeger 
> Currently the button, to switch between modes, is in the Welcome.vue, but that means there is no way to switch modes in any other page.
I could add it to the navigation bar or leave it in the Welcome.vue.

What do you want? 
and this setting requires persistence, so in the future we'll have to add this setting to the user profile. just fyi.

**Comment by kat-hi** [comment]
> I could solve it 'ugly', by also asking what the current theme is in Login.vue, but I wondered if you could think of a better solution.

No I don't. 
I don't think this a problem and it's fine. 

I would like to increase the durability of the login expiration again (this changed in one of the last kubepotral backend releases). it will reduce the frequenzy of login-page calls.

**Comment by troeger** [comment]
The dark mode setting should be part of the user settings page, where you can change your primary mail address. The setting should be considered for all views after login.

**Comment by DenizCankurtaran** [comment]
For now I've positioned the button in profile besides the profile edit button.

Screenshot from 2020-12-01 09-02-07

**Review by kat-hi — APPROVED** [review]

**Pull request closed without merging**
