### PR TITLE
fixed persistant-storage

### PR DESCRIPTION
**Pull request by DenizCankurtaran**
Instead of using VuexPersist I switched to VuexPersistence

- https://www.npmjs.com/package/vuex-persist

I added the VuexPersistence to the store as a plugin which was missing in the previous version and also got rid of the reducer for now, since there doesn't exist much changing value

### CODE REVIEW

**Comment by kat-hi** [comment]
interesting. vuexPersist wasn't used, at least this wasn't intended.  instead I decided to use localStorage.
what kind of benefits do we have now? I thought VuexPersistence and localStorage are kind of equivalent but I didn't read enough to be sure.

**Comment by DenizCankurtaran** [comment]
As I've understood it, they are not equivalent localStorage is the way in Vue to handle states over multiple components, and VuexPersist is a plugin for the localStorage, that allows reloading in the browser without the loss of data.

As for benefits, one can now reload the Page without the localStorage resetting.
An admin for example lost the admin button after a reload, which now doesn't happen anymore.

**Comment by kat-hi** [comment]
I mean this kind of localStorage: https://vuejs.org/v2/cookbook/client-side-storage.html#Base-Example

**Comment by DenizCankurtaran** [comment]
Ah, I understand now, what I've done now is persisting the whole vuex storage, so it remains even after a refresh,
but you have already done so, with localStorage. So everything is saved twice now. I just found it odd that certain data was lost after a refresh, while others wasn't.

I can open another issue and look into why some data behaves weird.

**Comment by kat-hi** [comment]
maybe persisting the whole vuex storageis the better way to avoid re-requesting data

**Comment by kat-hi** [comment]
you could try to remove all the localStorage stuff and try to provide consistency with your solution, if you want to. just push new changes in this branch. and I'll review when it's done. would be great :)

**Review by kat-hi — APPROVED** [review]
nice, great job :+1:  :)

**Comment by kat-hi** [comment]
@DenizCankurtaran I just found a small bug related to "page reload". The data table adds the current state to the old state, which why each reload leads to more rows and duplicated data. do you want to fix it before merging? otherwise I'll create an Issue

**Pull request merged**
